server: 
  port: 8080
  #servlet: 
  #  context-path: /resource-server
logging:
  level:
    '[org.hibernate.stat]': debug
spring:
  jpa:
    show-sql: true
    properties:
      '[hibernate.format_sql]': true
      '[hibernate.generate_statistics]': true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:postgresql://localhost:5432/odontolab
    username: odontolab
    password: odontolab
    driver-class-name: org.postgresql.Driver
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8083/auth/realms/baeldung
#          jwk-set-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs